tinywl: fix duplicate object files passed to linker
On BSD make, $> is an alias for $^. On both GNU and BSD make, $^
is supported. Specifying both resulted in duplicate object files
passed to the linker:

    ld: error: duplicate symbol: main
    >>> defined at tinywl.c:887
    >>>            tinywl.o:(main)
    >>> defined at tinywl.c:887
    >>>            tinywl.o:(.text+0x0)
    cc: error: linker command failed with exit code 1 (use -v to see invocation)

Only use $^ and remove $>.

(cherry picked from commit 322291cdcfe1ea29fd6987f4922c90c5a2798d18)